site:
  title: USFM-USX-USJ Documentation
  url: https://docs.usfm.bible
  start_page: usfm::index.adoc
  robots: allow
git:
  ensure_git_suffix: true
content:
  sources:
    - url: https://github.com/usfm-bible/tcdocs.git
      branches: [main, 3.1, 3.1.1]
      start_path: manual/antora
output:
  dir: ./build/site
asciidoc:
  attributes:
    example-caption: false
    listing-caption: false
    page-pagination: ''
    url-org: https://usfm.bible
    url-project: https://docs.usfm.bible
  extensions:
    - '@asciidoctor/tabs'
ui:
  bundle:
    # Antora default UI
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
runtime:
  fetch: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      snippet_length: 100
  #  - '@antora/pdf-extension'
